#!/usr/bin/env bash
# Create a secure ambassador client to link two Docker containers together over an
# untrusted connection. Requires both the client and server to have access to the same
# etcd cluster. The cluster does not need to be trusted. However, a DOS attack is trivial
# if the cluster is compromised and problems may occur if the wrong server and clients
# become connected.
#
# Usage:
#     TLS_KEY=path/to/key $0 container_name external_ip
#
# Connects to a container named container_name. The external_ip is *this* host's IP
# address.
#
# Assumes the environment variable VAPR_CERTSTORE is set to the directory containing
# certificates, including the root CA at ca.crt. These are set as part of vapr
# (https://github.com/SojournLabs/vapr), although you can set them manually.


if [[ "${TLS_KEY}" == "" ]]; then
    echo "No key file specified using environment variable TLS_KEY."
    exit 1
fi

KEY_FILE=$(cd $(dirname ${TLS_KEY}); pwd)/$(basename ${TLS_KEY})

CONTAINER=$1
if [[ "${CONTAINER}" == "" ]]; then
    echo "No container was specified."
    exit 1
fi

docker run -v /var/run/docker.sock:/var/run/docker.sock -v ${VAPR_CERTSTORE:=`pwd`/certstore}:/vapr/certstore:ro -v ${KEY_FILE}:/vapr/keys/$(basename ${KEY_FILE}):ro --rm -t -i ${PORTS} --name ${CONTAINER}_ambassador_client sojournlabs/ambassador client $*
